id: PB154D131
initial_creation_type: input
source_metadata:
  title: Auspiciousness Series
  language: en
  description: 'A selection of texts on the theme of auspiciousness (maṅgalam; bkra
    shis) including verses of auspiciousness (maṅgalagāthā) and prayers:'
  volume:
    2845cd55acd24027a164b7041b5e0a43:
      title: A Prayer for Auspiciousness
      parent: Verses of Auspiciousness
    330d7e717ff645f59e16b749f0c4e652:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Verses of Auspiciousness
    873334c9fa024aa495d71c06b08f2557:
      title: Verses of Auspiciousness
      parent: Verses of Auspiciousness
    b78b56bbd48542b18862f4bb2ab5d7c7:
      title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness
        and Wellbeing'
      parent: Verses of Auspiciousness
    b32c7c57dab7435abbff62a0acbf0500:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Verses of Auspiciousness
created_at: '2022-03-01T02:52:02.799091'
last_modified_at: '2022-03-01T02:52:02.799097'
